- name: Delete resources for reverse proxy stuffs
  hosts: all
  strategy: linear
  become: false

  tasks:

    - name: Create Kubeconfig temporary file
      tempfile:
        state: file
        prefix: rptests
      register: kubeconfig_file

    - name: Copy KubeConfig in a temporary file
      copy:
        content: "{{ kubeConfig }}"
        dest: "{{ kubeconfig_file.path }}"

#    - name: Remove RM Ingress
#      k8s:
#        state: absent
#        api_version: networking.k8s.io/v1beta1
#        kind: Ingress
#        namespace: "{{ zoneNamespace }}"
#        name: "rp-{{ uc_id }}-ingress"
#        kubeconfig: "{{ kubeconfig_file.path }}"

#    - name: Remove RM Service
#      k8s:
#        state: absent
#        api_version: v1
#        kind: Service
#        namespace: "{{ zoneNamespace }}"
#        name: "rp-{{ uc_id }}-svc"
#        kubeconfig: "{{ kubeconfig_file.path }}"

#    - name: Remove RM Deployment
#      k8s:
#        state: absent
#        api_version: apps/v1
#        kind: Deployment
#        namespace: "{{ zoneNamespace }}"
#        name: "rp-{{ uc_id }}"
#        kubeconfig: "{{ kubeconfig_file.path }}"

    - name: Remove RM Ingress
      shell: "kubectl --kubeconfig {{ kubeconfig_file.path }} -n {{ zoneNamespace }} delete ingress rp-{{ uc_id }}-ingress"
      ignore_errors: yes

    - name: Remove RM Service
      shell: "kubectl --kubeconfig {{ kubeconfig_file.path }} -n {{ zoneNamespace }} delete service rp-{{ uc_id }}-svc"
      ignore_errors: yes

    - name: Remove RM Deployment
      shell: "kubectl --kubeconfig {{ kubeconfig_file.path }} -n {{ zoneNamespace }} delete deployment rp-{{ uc_id }}"
      ignore_errors: yes

    - name: Delete nginx configMap
      shell: "kubectl --kubeconfig {{ kubeconfig_file.path }} -n {{ zoneNamespace }} delete configmap rp-{{ uc_id }}-nginx-cm"
      ignore_errors: yes

    - name: Delete settings configMap
      shell: "kubectl --kubeconfig {{ kubeconfig_file.path }} -n {{ zoneNamespace }} delete configmap rp-{{ uc_id }}-settings-cm"
      ignore_errors: yes

    - name: Delete site configMap
      shell: "kubectl --kubeconfig {{ kubeconfig_file.path }} -n {{ zoneNamespace }} delete configmap rp-{{ uc_id }}-site-cm"
      ignore_errors: yes

    - name: Delete app configMap
      shell: "kubectl --kubeconfig {{ kubeconfig_file.path }} -n {{ zoneNamespace }} delete configmap rp-{{ uc_id }}-app-cm"
      ignore_errors: yes

    - name: Finally remove kubeconfig temporary file
      file:
        path: "{{ kubeconfig_file.path }}"
        state: absent
